#include <homekit/types.h>

#define HEATER_COOLER_INACTIVE 0
#define HEATER_COOLER_ACTIVE 1

#define HEATER_COOLER_STATE_INACTIVE 0
#define HEATER_COOLER_STATE_IDLE 1
#define HEATER_COOLER_STATE_HEATING 2
#define HEATER_COOLER_STATE_COOLING 3

#define HEATER_COOLER_TARGET_STATE_AUTO 0
#define HEATER_COOLER_TARGET_STATE_HEAT 1
#define HEATER_COOLER_TARGET_STATE_COOL 2

#define HEATER_COOLER_SWING_DISABLED 0
#define HEATER_COOLER_SWING_ENABLED 1

extern homekit_service_t service_heater_cooler;

extern homekit_characteristic_t ch_heater_cooler_active;
extern homekit_characteristic_t ch_target_heater_cooler_state;
extern homekit_characteristic_t ch_current_heater_cooler_state;
extern homekit_characteristic_t ch_cooling_threshold_temperature;
extern homekit_characteristic_t ch_heating_threshold_temperature;
extern homekit_characteristic_t ch_heater_cooler_rotation_speed;
extern homekit_characteristic_t ch_heater_cooler_swing_mode;
extern homekit_characteristic_t ch_heater_cooler_current_temperature;
